### ISSUE TITLE
Cannot use mlflow.log_artifacts to upload to mlflow tracking server

### ISSUE THREAD

**Issue by anhquan075** [sachua/mlflow-docker-compose#22]
I've deployed a mlflow tracking server by using this repo. This works like a charm but when I use `mlflow.log_artifacts` to upload to the tracking servers, I faced this issue. Can anyone fix this bug, please?
![image](https://user-images.githubusercontent.com/54442768/188606884-216a07b9-1feb-4c06-a452-1e1450d25996.png)

**Comment by sachua** [comment]
Can you check if you specified your MinIO credentials?
Your output looks like Jupyter Notebook, maybe you can try running this in a cell:
```
%%capture
!pip install --upgrade pip --user
!pip install mlflow[extras] --user
%env MLFLOW_TRACKING_URI=http://host:port
%env MLFLOW_S3_ENDPOINT_URL=http://host:port
%env AWS_ACCESS_KEY_ID=minio
%env AWS_SECRET_ACCESS_KEY=minio123
```
