### ISSUE TITLE
the bucket is not created on docker-compose up command

### ISSUE THREAD

**Issue by MChrys** [sachua/mlflow-docker-compose#5]
![minio](https://user-images.githubusercontent.com/18635108/139534262-a6c8ba37-4252-4b55-be36-7c21c6a9adac.png)
Even if it is display that  the bucket should be created there are nothing on the server
![miniosrv](https://user-images.githubusercontent.com/18635108/139534305-ed2e63f6-d255-4fd4-a0e5-cae5b894ce16.png)

**Comment by MChrys** [comment]
the experiement is running wel
![mlrun](https://user-images.githubusercontent.com/18635108/139536523-30e161a9-5861-43ed-b2ce-b09aa0231925.png)
l 
but I get Erreur on mlflow_server container
![errorcompose](https://user-images.githubusercontent.com/18635108/139536544-a826f005-2d86-46f8-b5b9-62ade1895b3d.png)

**Comment by MChrys** [comment]
After I create the bucket manually 
I get this error :
![unable](https://user-images.githubusercontent.com/18635108/139541031-42063818-c04e-4ebe-b09b-de8216bf4b70.png)

**Comment by sachua** [comment]
> After I create the bucket manually I get this error : ![unable](https://user-images.githubusercontent.com/18635108/139541031-42063818-c04e-4ebe-b09b-de8216bf4b70.png)

was the credential file path ~/.aws/credentials?

**Comment by sachua** [comment]
> ![minio](https://user-images.githubusercontent.com/18635108/139534262-a6c8ba37-4252-4b55-be36-7c21c6a9adac.png) Even if it is display that the bucket should be created there are nothing on the server ![miniosrv](https://user-images.githubusercontent.com/18635108/139534305-ed2e63f6-d255-4fd4-a0e5-cae5b894ce16.png)

it seems like you made some changes to mc, but from the error message:
```bash
<ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-v59rnt9uo60g/?location=": dial TCP 172.18.0.4:9000: connect: connection refused.
```
The bucket was not created because it was unable to set the alias minio to point to your minio s3 bucket. You might have to check the credentials you set for your minio s3.

**Comment by MChrys** [comment]
> > After I create the bucket manually I get this error : ![unable](https://user-images.githubusercontent.com/18635108/139541031-42063818-c04e-4ebe-b09b-de8216bf4b70.png)
> 
> was the credential file path ~/.aws/credentials?

I set the .aws folder in the current directory mlflow-docker-compose

**Comment by MChrys** [comment]
> > ![minio](https://user-images.githubusercontent.com/18635108/139534262-a6c8ba37-4252-4b55-be36-7c21c6a9adac.png) Even if it is display that the bucket should be created there are nothing on the server ![miniosrv](https://user-images.githubusercontent.com/18635108/139534305-ed2e63f6-d255-4fd4-a0e5-cae5b894ce16.png)
> 
> it seems like you made some changes to mc, your mc container is hitting permission denied when it tries to run the `wait-for-it.sh`, which will result in your mc service to try to create the bucket before your minio service is ready.
> 
> From the error message:
> 
> ```shell
> <ERROR> Unable to initialize new alias from the provided credentials. Get "http://minio:9000/probe-bucket-sign-v59rnt9uo60g/?location=": dial TCP 172.18.0.4:9000: connect: connection refused.
> ```
> 
> The bucket was not created because it was unable to set the alias minio to point to your minio s3 bucket. You might have to check the credentials you set for your minio s3. But it might also be due to your minio service not ready before the alias set command was run.

I resolved the credidential error with export variable env instead of .aws/credentials, because I shouldn't have create it in the current folder of the project I guess, but I have no idea where I should move it

**Comment by sachua** [comment]
try creating the config file in ~/.aws
```bash
cat > ~/.aws/credentials <<EOF
[default]
aws_access_key_id=minio
aws_secret_access_key=minio123
EOF
```

**Comment by sachua** [comment]
> try creating the credentials file in ~/.aws
> 
> ```shell
> cat > ~/.aws/credentials <<EOF
> [default]
> aws_access_key_id=minio
> aws_secret_access_key=minio123
> EOF
> ```

**Comment by sachua** [comment]
try creating the credentials file in ~/.aws
```bash
cat > ~/.aws/credentials <<EOF
[default]
aws_access_key_id=minio
aws_secret_access_key=minio123
EOF
```

**Comment by sachua** [comment]
If you run a `chmod +x wait-for-it.sh` before doing a `docker-compose up`, the permission denied error should be resolved.

**Comment by MChrys** [comment]
> If you run a `chmod +x wait-for-it.sh` before doing a `docker-compose up -d --build`, the permission denied error should be resolved.

Perfect it was the problem, chmod solve it
