### ISSUE TITLE
try creating the credentials file in ~/.aws

### ISSUE THREAD

**Issue by MChrys** [sachua/mlflow-docker-compose#7]
try creating the credentials file in ~/.aws
```bash
cat > ~/.aws/credentials <<EOF
[default]
aws_access_key_id=minio
aws_secret_access_key=minio123
EOF
```
you can see where boto3 tries to find the credentials here: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

_Originally posted by @sachua in https://github.com/sachua/mlflow-docker-compose/issues/5#issuecomment-955712311_

**Comment by MChrys** [comment]
this command is doesn't working you need too use " " somewhere to make it work in the bash I guess

**Comment by sachua** [comment]
It might be due to your environment set-up that is causing the command to not work, but the main point was that you should create that file in `~/.aws`, the file name should be `credentials`, and it should contain
 ```
[default]
aws_access_key_id=minio
aws_secret_access_key=minio123
```
