### ISSUE TITLE
Jupyter notebook fails storing artefacts

### ISSUE THREAD

**Issue by NuwanCW** [sachua/mlflow-docker-compose#9]
Hi Jpyter notebook fails on saving artefacts but script running the terminal works fine. The error says An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records. Do you know how to fix this please?
Thanks

**Comment by sachua** [comment]
Check if ~/.aws/credentials contains the correct credentials, echo $AWS_SECRET_ACCESS_KEY and $AWS_ACCESS_KEY_ID if there are values already set
