### ISSUE TITLE
model deployment

### ISSUE THREAD

**Issue by StathisKap** [sachua/mlflow-docker-compose#96]
Hello,

FIrst, of all I want to say that this a great repo. Thank you for making it very easy to use.

I wanted to say that the`mlflow models serve -m S3://mlflow/0/98bdf6ec158145908af39f86156c347f/artifacts/model -p 1234` didn't work for me unless I added `--env-manager conda`. 

Also, I had to downgrade my python on the new env created by `mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=0.42`.

Lastly, I couldn't get the curl request to work. It says that the scoring protocol has changed but I can't figure out what has it changed to. And I couldn't find a swagger or anything so not really sure what to do for the example one.

Thank you again for this. Great work

**Comment by sachua** [comment]
Hi, thanks for your feedback! I have updated the README.md. Unfortunately https://github.com/mlflow/mlflow-example.git depends on mlflow, so I had to fork it and make my edits to their outdated example, but it should work fine now.
